package com.example.renting_app;

import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.Button;

// this activity is generated by intro_activity
// it began once connection to server REST is successsful
public class SigningActivity extends AppCompatActivity {

    Button sign_in_b;
    Button sign_up_b;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_signing);

        sign_in_b= (Button)findViewById(R.id.sign_inB);
        sign_in_b.setOnClickListener(v -> {
            // move into singing in fragment

        });

    }
}